version: "3"
services:
  frontend-service:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DOMAIN=${DOMAIN}
  backend-service:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:80"
